Index: gmsh-2.0.8/Makefile
===================================================================
--- gmsh-2.0.8.orig/Makefile	2007-12-16 16:13:52.000000000 +0100
+++ gmsh-2.0.8/Makefile	2007-12-16 16:14:14.000000000 +0100
@@ -49,11 +49,11 @@
 	rm -f bin/gmsh_i386 bin/gmsh_ppc
 
 install: variables
-	mkdir -p ${bindir}
-	cp -f bin/gmsh${EXEEXT} ${bindir}
-	chmod 755 ${bindir}/gmsh${EXEEXT}
-	mkdir -p ${mandir}/man1
-	cp -f doc/gmsh.1 ${mandir}/man1
+#	mkdir -p ${bindir}
+#	cp -f bin/gmsh${EXEEXT} ${bindir}
+#	chmod 755 ${bindir}/gmsh${EXEEXT}
+#	mkdir -p ${mandir}/man1
+#	cp -f doc/gmsh.1 ${mandir}/man1
 
 install-mac: variables package-mac
 	cp -rf gmsh-${GMSH_VERSION}/Gmsh.app /Applications
